# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-SE90XLJGB0'

menu:
- {name: 'About',   url: 'about'}
- {name: 'Research', url: 'research'}
- {name: 'Publications', url: 'publications'}
- {name: 'Gallery', url: 'gallery'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope',       link: 'mailto:kplin@zoology.ubc.ca'}
- {icon: 'github',         link: 'https://github.com/kpsimonlin'}
- {icon: 'researchgate',     link: 'https://www.researchgate.net/profile/Kung-Ping-Lin'}
- {icon: 'google-scholar', link: 'https://scholar.google.com.tw/citations?hl=zh-TW&user=EJPYBs8AAAAJ'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
